version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: messagepunk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:management
    container_name: messagepunk-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBIMQ_HOSTNAME: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: messagepunk-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: messagepunk
      MINIO_ROOT_PASSWORD: messagepunk
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 messagepunk messagepunk;
      /usr/bin/mc mb myminio/messagepunk;
      /usr/bin/mc policy set public myminio/messagepunk;
      exit 0;
      "


volumes:
  redis_data:
  rabbitmq_data:
  mongodb_data:
  minio_data:

networks:
  app-network:
    external: true
    driver: bridge