apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
      - name: file-service
        image: siddpunk/messagepunk-file-service
        ports:
        - containerPort: 4300
        env:
        - name: PORT
          value: "4300"
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: messagepunk-secret
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: messagepunk-secret
              key: S3_SECRET_ACCESS_KEY
        - name: S3_BUCKET
          value: "messagepunk"
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: messagepunk-secret
              key: S3_REGION
        - name: S3_ENDPOINT
          value: "http://minio:9000"

---

apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  selector:
    app: file-service
  ports:
    - protocol: TCP
      port: 4300
      targetPort: 4300
  type: ClusterIP