apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: messagepunk.com
    http:
      paths:
      - path : /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 4000
      - path : /api/socket
        pathType: Prefix
        backend:
          service:
            name: socket-service
            port:
              number: 4200
      - path : /api/db
        pathType: Prefix
        backend:
          service:
            name: db-service
            port:
              number: 4100
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
